"""Smoke-test the deployed Apps Script web app.

Posts a single test row to the sheet-writer endpoint over plain HTTPS. Run
this once after deploying apps_script/SheetWriter.gs, before trusting the
cron to write real rows.

Usage:
    python scripts/smoke_test.py <SHEET_WRITER_URL>
"""
from __future__ import annotations
import json
import os
import sys
import urllib.request
import urllib.error
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), "..", ".env"))


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/smoke_test.py <SHEET_WRITER_URL>")
        sys.exit(2)

    web_app_url = sys.argv[1].strip()
    token = os.environ.get("SHEET_WRITER_TOKEN")
    if not token:
        print("SHEET_WRITER_TOKEN not set - copy .env.example to .env and fill it in.")
        sys.exit(2)

    payload = {
        "token": token,
        "rows": [{
            "status": "Skipped",
            "owner": "smoke-test",
            "difficulty": "Easy",
            "mention_product": "No",
            "sub": "r/test",
            "title": "Smoke-test row (delete me)",
            "url": "https://example.com",
            "age": "0h",
            "upvotes": 0,
            "comments": 0,
            "op": "u/smoke-test",
            "op_signals": "",
            "score": 0,
            "summary": "Test row produced by scripts/smoke_test.py",
            "suggested_draft": "(smoke-test)",
            "posted_url": "",
            "notes": "Generated by scripts/smoke_test.py - safe to delete",
        }],
    }

    req = urllib.request.Request(
        web_app_url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    print(f"Posting smoke-test row to:\n  {web_app_url}\n")
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            status = r.status
            body = r.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as e:
        status = e.code
        body = e.read().decode("utf-8", "replace")

    print(f"Status: {status}")
    print(f"Body:   {body[:500]}")

    if status == 200 and ('"ok":true' in body or '"appended":1' in body):
        print("\nSUCCESS: web app accepted the test row.")
        sys.exit(0)
    print(f"\nFAIL: expected ok:true response, got status={status}.")
    sys.exit(1)


if __name__ == "__main__":
    main()
